#!/bin/sh

# the serial port where wind data is read from
WIND_DATA_SOURCE=/dev/ttyO1

# where the wind data is continuously stored
WIND_LOG=/var/log/wind

# program to split wind data log by day
ROTATE_LOGS=/usr/sbin/rotatelogs
LOG_ROTATION_FREQ=86400

# tag with timestamp
perl -ne 'print time() . "\t" . $_' < $WIND_DATA_SOURCE |
    $ROTATE_LOGS -l -f -L $WIND_LOG $WIND_LOG.%Y-%m-%d $LOG_ROTATION_FREQ


#  -v       Verbose operation. Messages are written to stderr.
#  -l       Base rotation on local time instead of UTC.
#  -L path  Create hard link from current log to specified path.
#  -p prog  Run specified program after opening a new log file. See below.
#  -f       Force opening of log on program start.
#  -D       Create parent directories of log file.
#  -t       Truncate logfile instead of rotating, tail friendly.
#  -e       Echo log to stdout for further processing.
#  -c       Create log even if it is empty.

